desc "Compile the tex files to dvi"
task :compile do
  sh "latex talk.tex"
end

desc "Convert the dvi to ps file"
task :dvips => :compile do
  sh "dvips talk.dvi"
end

desc "Convert the ps to pdf file"
task :pstopdf => :dvips do
  sh "ps2pdf talk.ps"
end

task :default => :pstopdf
